### ISSUE TITLE
creating a harddisk under vmware

### ISSUE THREAD

**Issue by roelandjansen** [roelandjansen/pcmos386v501#1]
if vmware is used to build a harddisk based setup, you can use the image file as supplied.

Depending on the size of the disk you create, you cannot msys, format the disk at all and  the command processor ($$shell.sys) will show weird characters incorrect sizes etc al.

I believe that fdisk/format/$$shell.sys needs some TLC here

Maybe issue #2 is also affected

**Comment by Wack0** [comment]
Does this reproduce on an emulator of period hardware (like 86Box), rather than a virtualiser that provides a modern system?

**Comment by roelandjansen** [comment]
I presume it won't happen  on older hardware and that sizing of disks etc causes this.
I am not sure though. I can reproduce it under vmware workstation 12 for sure.

**Comment by roelandjansen** [comment]
got it going with a small disk (40MB) and 64MB memory. Closing for now. Large disk support is probably somethig for the next life..
