### ISSUE TITLE
Repository contains intermediate _*.SYS

### ISSUE THREAD

**Issue by dcoshea** [roelandjansen/pcmos386v501#11]
As at 2d19bc1, `SOURCES/src/mos5src` contains a number of files which appear to be redundant intermediate build artefacts.

    _286N.SYS
    _386.SYS
    _ALL.SYS
    _ARNET.SYS
    _CHARGE.SYS
    _EMS.SYS
    _GIZMO.SYS
    _KBBE.SYS
    _KBCF.SYS
    _KBDK.SYS
    _KBFR.SYS
    _KBGR.SYS
    _KBIT.SYS
    _KBLA.SYS
    _KBNL.SYS
    _KBNO.SYS
    _KBPO.SYS
    _KBSF.SYS
    _KBSG.SYS
    _KBSP.SYS
    _KBSV.SYS
    _KBUK.SYS
    _MOUSE.SYS
    _NETBIOS.SYS
    _PIPE.SYS
    _RAMDISK.SYS
    _SERIAL.SYS
    __SHELL.SYS

For each of those files, a corresponding file exists in the same directory with 1-2 leading underscores replaced with `$`, and that corresponding file is identical.  The only exception is `_SERIAL.SYS` whose corresponding identical file is called `$$SERIAL.SYS` (i.e. one underscore is replaced with two dollar signs).

Also, the corresponding `$*.SYS` versions are in `SHIPMOS/SHIPMOS.ZIP` (file content comparisons were not performed here), confirming that the `$*.SYS` filenames are used for shipping whereas the `_*.SYS` filenames are just intermediate build artefacts.  There are two exceptions to this:
- `$KBUK.SYS` is not present in `SHIPMOS/SHIPMOS.ZIP`, which instead contains two files `$KBUK3.SYS` and `$KBUK4.SYS`; and
- `$$SERIAL.SYS` , is not present in `SHIPMOS/SHIPMOS.ZIP`, which contains a corresponding filename with only one dollar sign.
These exceptions don't invalidate the assumption that the `_*.SYS` files are intermediate build artefacts.

Given the above, it seems like the files whose names are listed above don't belong in the repository as they are intermediate build products, and once you run `MAKEMOS.BAT` and it performs the renaming steps (see issues #6 and #7) those files should all disappear, resulting in `git status` showing those files as having been deleted.

**Comment by andrewbird** [comment]
After #37 was merged these are no longer in the build directory, so I believe this can be closed.

**Comment by the-grue** [comment]
> After #37 was merged these are no longer in the build directory, so I believe this can be closed.

I'll second that.

**Comment by roelandjansen** [comment]
closed.
