### ISSUE TITLE
Document release process and/or identify files that are shipped

### ISSUE THREAD

**Issue by dcoshea** [roelandjansen/pcmos386v501#12]
There doesn't appear to be a document, batch file or makefile describing how a release to customers is/was made.  For example, `IMAGES/PCMOS386-9-user.img` appears to contain a working installation, and if I wanted to modify and recompile `$$SHELL.SYS`, it would be easy to just copy it into that disk image.  However, what if I wanted to rebuild everything (e.g. with different compiler flags) and make sure all the changes work?  Perhaps this was a manual process that involved referencing an existing disk.

Also, are there binaries that can be built, which aren't in `PCMOS386-9-user.img`, but which are useful for users of the product?

It seems like it would be useful to create a table listing all of the files which were released - either in `PCMOS386-9-user.img` or any of the files in the `SHIPMOS` directory - showing which of those images/zip files contained the given file, plus the directory or directories in which that file is built/found (if any), and perhaps the makefile that generates it (if any).  This would help with understanding issues like issue #11, as it would make it clear that those files are intermediate rather than files that are shipped.  It would also help with understanding the source tree, plus working out whether "everything" is being successfully rebuilt (see also issue #9 which notes that `MAKEMOS.BAT` won't rebuild everything by default given that the targets are also in the Git repository; even after adding the `-u` option to `make`, I don't know for sure that everything is rebuilt, and until I know that and have tested the built files it's hard to know what build environment is ideal (issue #8)).

**Comment by src153** [comment]
@the-grue sorting out the mess. Closing.
