### ISSUE TITLE
Please update wiki page

### ISSUE THREAD

**Issue by stsp** [roelandjansen/pcmos386v501#15]
Now as pcmos was released under GPL, I think
it would be very interesting for people to know what
the heck is this all about. :)

Wikipedia has this article:
https://en.wikipedia.org/wiki/PC-MOS/386
but it is very brief and only suits for historical needs.
For example it states that
`It required a memory management unit (MMU) to support memory protection, so was not compatible with 8086 and 8088 processors.` and yet people
are now running it under dosemu2 - the vm that
only supports realmode + DPMI.

https://virtuallyfun.com/2011/02/02/pc-mos386/
This article states `PC-MOS 5.0 also cannot run DPMI programs, which is a shame.`
but I wonder what does this mean: does it lack its
own dpmi server, or any other DPMI server cannot
be used with it?

So it would be really very nice if someone takes
time to extend the wikipedia article, writing about
the pcmos architecture, status, DOS compatibility,
CPU compatibility, VM compatibility (under what
VMs it can be running), compilers compatibility, etc etc.

**Comment by roelandjansen** [comment]
the good part about wiki pages is that anyone can change it. 

I'll certainly pick up parts of it.

**Comment by roelandjansen** [comment]
regarding the DDPMI specification -- at the time v5.01 was released, there was no DPMI support. I know (top of head) that Stewart Hyde (SAH) was busy implementing stuff and the code is also in the repo but not finished. (In fact the system would crash).

It would be cool if someone who understands all the protected mode stuff, translate lookaside buffesr etc etc more than I do, could take a shot at it. It's open source now ;-)

**Comment by stsp** [comment]
I wanted to change it myself, but failed
to google for the needed info.
Maybe if you could give a brief explanation,
that would be easier. :) No native DPMI
support is fine as long as any standalone
DPMI server can work - so does it work?
As for protected mode, it seems like it does
not use protected mode by default. My
current guess is that you need
`memdev = \mos\$386.sys /p` in config.sys
for it to start using protected mode - is this
correct? So basically its like DOS with emm386.exe
putting it in prot mode - is this comparison
remotely valid?

**Comment by roelandjansen** [comment]
Hmm, I -at this time- am not sure, Stas.

I know that there is some documentation out there but I am afraid I ditched my manuals long time ago.
Stewart is here too somewhere ;-) so maybe he could refresh some parts here.

**Comment by 3FLLC** [comment]
Yes, it would be great if *anyone* could share the original manuals. How to setup users/tasks, switch between them on the main console. I was able to fork the master, and have documented how to boot from the IMAGES/*.img and step by step to build a self-booting disk image.

Do you (or anyone) know where the boot loader source is located on this repository, and I will start from there forward. I am very keep on 16bit/32bit MOS - especially if I can get it to boot and run (I know tons of work) natively on my Raspberry Pi. I have tons of DOS code I want to port to the Pi.

**Comment by src153** [comment]
Project Wiki open now, items mentioned here are " what if maybe ", not relevant to current work being done. Closing.
