### ISSUE TITLE
Remove BRIEF directory

### ISSUE THREAD

**Issue by dcoshea** [roelandjansen/pcmos386v501#18]
The presence and content of `BRIEF/README.md` led me to believe that the Brief editor was required - I supposed that it might have some form of project file capability as some IDEs do, and that this was required for building.  Others seem to have had some of the same thoughts, see e.g. issue #14 and 
[this blog post](https://virtuallyfun.superglobalmegacorp.com/2017/09/03/pc-mos386-v5-01-released-gpl-v3-0).

To make things less confusing, it would probably make sense to remove the `BRIEF` directory.

However, I'm sure almost everyone looking at this project is interested in its history, so perhaps a document could be added explaining some things like "Development at TSL was performed on PCs using version 3.1 of the Borland Brief editor" and other interesting (but not necessarily important from the perspective of building) recollections.

**Comment by roelandjansen** [comment]
David, 

good point. I'll leave it for history purposes and will clarify it as well.
The stuff can be edited with all you want including vim, sublime, whatever.
I also will note that the building itself is/can be done under PC-MOS/386 itself.
