### ISSUE TITLE
Question: What are the bare minimum files require to boot PC-MOS

### ISSUE THREAD

**Issue by andrewbird** [roelandjansen/pcmos386v501#19]
I'm trying to get dosemu2's native bootloader to boot PC-MOS, see https://github.com/stsp/dosemu2/issues/502. What are the minimum files required to boot the system? For example:

On MS-DOS
~~~
IO.SYS
MSDOS.SYS
COMMAND.COM
~~~
From watching PC-MOS try to boot I wonder if the following is the correct set?
~~~
$$MOS.SYS
$$SHELL.SYS
COMMAND.COM
~~~

**Comment by roelandjansen** [comment]
that is enough to boot, yes.
