### ISSUE TITLE
Booting from hard disk fails if floppy drives are disabled after installation

### ISSUE THREAD

**Issue by andrewbird** [roelandjansen/pcmos386v501#21]
If PC-MOS is installed from floppy disk to hard disk after which the floppy disks are disabled, booting from the hard disk is no longer possible as the boot process becomes confused about the location of command.com. There's a long discussion over at https://github.com/stsp/dosemu2/issues/502, where it seems that although $MOS.SYS wants to open C:\COMMAND.COM, C: is no longer deemed valid as in the MOS BDB linked list the only drive is number '00'. This is the result:
![pcmos-no-floppy-with-bootblk](https://user-images.githubusercontent.com/220835/32146696-4b69d664-bcd3-11e7-94cb-a2bf1ac9c681.png)

**Comment by roelandjansen** [comment]
thanks for the feedback
