### ISSUE TITLE
Working VM

### ISSUE THREAD

**Issue by ebrelion** [roelandjansen/pcmos386v501#32]
Perhaps someone can be kind enough to setup a virtualbox VM including all needed tools and source tree and share it with others ?

**Comment by src153** [comment]
If someone did, it would include non-free tools like Borland C++ 3.1. I don't worry that Borland might pursue anyone for using it. If they want to stop people, the first thing they should do is send a takedown notice to winworldpc.com, which hosts it.

Still, technically, you're asking people to disregard intellectual property rights. Maybe you could do it yourself, then share with us?

Personally I don't have a problem with it. The Chinese steal anything not nailed down and laugh all the way to the bank. Westerners are comparatively naive and self righteous over their intellectual property rights. People need to wake up and see the big picture. The entire fiat money system and the central banks are scamming you every day. Listen to Max Keiser on the Keiser report and get educated.

On the subject of Borland C++, releases prior to 3.1, plus the related Turbo C++ versions, are all known to be buggy. That's another reason NOT to port the code back to the freely available 1.01.

**Comment by drawkula** [comment]
Wouldn't a download, unpack and install script in such a VM be enough?
With automagic fallback to a copy at Archive.Org?

**Comment by src153** [comment]
Sounds like an idea. Maybe DOS as the OS to keep it small? I was able to build the kernel on a real DOS machine. That's as far as I went. I'm waiting for the manual to appear before I spend much more time on the source code.

**Comment by drawkula** [comment]
Having a 3 disk (or partition) VM setup (DOS, MOS-Source, MOS-install-target) would always run the toolchain in a well understood and constant environment.

Running the toolchain on MOS might show unexpected bugs only showing up there and if such things happen, knowledge about BC on MOS probably is near to absent in our favourite internet indexing robots...

**Comment by src153** [comment]
Nothing further, closing
