### ISSUE TITLE
pc-mos newsgroup

### ISSUE THREAD

**Issue by src153** [roelandjansen/pcmos386v501#38]
I hit some resistance trying to create a USENET newsgroup. Seems that people don't want to create a new group unless the subject is already active in other groups. Chicken vs egg problem.

But there are countless dead groups (they're hard to get rid of) we could hijack for our own use. Here are two relevant ones:

alt.comp.os.ms-dos
alt.msdos.programmer

But the hard part is getting today's generation to use a newsreader instead of a web interface.

**Comment by src153** [comment]
If there is no interest, I will close this and carry on. People don't know what they're missing. Or maybe old timers do. I tried.

**Comment by drawkula** [comment]
Please leave this issue open so maybe someone having an idea will see it later.

**Comment by src153** [comment]
On USENET the party never ends

**Comment by drawkula** [comment]
For transparency: I just have put the following into [SDF](https://sdf.org/)'s BBOARD (an internal BBS like system).
```
TACKER:  yeti (yeti)
SUBJECT: PC-MOS
DATE:    19-Jan-19 17:01:57
HOST:    sdf

-=<1>=-

The project 

        https://github.com/roelandjansen/pcmos386v501
        PC-MOS/386 v5.01 final release including cdrom driver sources.

is trying to put the pieces of this multitasking OS together again.


-=<2>=-

And especially:

        https://github.com/roelandjansen/pcmos386v501/issues/38
        pc-mos newsgroup #38 

Does someone here know how to get a newsgroup founded?
Please answer this at github.


-=<3>=-

I'm not a member of that project, just an old unix beard curiously watching 
their mission.
```

Maybe this yields some newsgroup related answers or some other interesting synergies.

**Comment by roelandjansen** [comment]
for me it's not hard to use an usenet reader et al but the biggest issues I face is that I need for every channel some different thing done.

Look at whatsapp -- noohhhh I use Telegram! Ok, I also use TG then, next to WA. But heyyyy I use threema! Ok, instakling threema. And the list continues. So I have quite a lot of feeds left and right and there is a moment when channeling the information is needed.

And FWIW -- I already have between 500 and 1000+ messages on a daily basis and not counting the chaos created with teams, wiki's apps, skype, mail and so on. 

Currently most of the work is combing out the relevant stuff.

**Comment by src153** [comment]
What I dislike about github, or learning it, is that all the messages are not in one place. I get emails for each one, but some are in issues, some are in commits, and who knows where else. With email messages, I don't save them for later search because I like to keep my email clean. My USENET newsreader is better suited for archive and search. I don't trust 3rd parties like google to hold things for me. I want no clouds in my sky!

Old folks like me don't want to learn new stuff, and youngsters don't want to learn old stuff. I wonder why are they here, messing around with PC-MOS from the 80's?

I use linux, but I got started with it when I was young enough to care about new things. Those who live long enough to get old, may someday understand.

**Comment by drawkula** [comment]
A newsgroup would not replace the communication here in GitHub and because most of it is tied to commits, code and issues, this kind of communication really should happen only here.

The newsgroup may make sense for stuff that is not tightly related to the code.

The structure of mail and a mail user agent are not so different from news and a newsreader. With some folders and automatic sorting you probably can let your MUA sort all stuff in a newsgroup like folder structure. Dig a bit for such features of your favourite MUA.

Additionally a 2nd repository (especially it's issues) can explicitly be dedicated to keep discussions not directly related to the development process. The issues' structure already is halfway a forum and I saw it being used in that way in [ForthHub/discussion](https://github.com/ForthHub/discussion).

This may be a way to keep things together by using only use Git(Hub) and mail.

----

One question remains: We can clone the code and we can clone the Wikis of projects. Can we somehow backup, clone, preserve what's happening in issues and PRs?

**Comment by src153** [comment]
I know what you are saying about MUAs. But the only MUA I use is gmail, and I don't use clouds any more than I have to.

I can't agree with

> this kind of communication really should happen only here

There's nothing sacrosanct about git or github. Some people don't use it. Why not SVN, why not CVS, why not RCS. Why not 80 column punched cards for that matter. They were good enough for the NASA moon landing. There are all kinds of gateways for all kinds of things. Why not?

Not that I expect it happen. Someone has to do some work. I'm arguing against the conformity mindset, just because.

**Comment by src153** [comment]
> One question remains: We can clone the code and we can clone the Wikis of projects. Can we somehow backup, clone, preserve what's happening in issues and PRs?

Github says you cannot, as I vaguely recall reading somewhere. But don't trust my memory, it's not always accurate. That's why I like to archive stuff. All in one place. All in my posession.

**Comment by src153** [comment]
> Additionally a 2nd repository (especially it's issues) can explicitly be dedicated ,,, may be a way to keep things together by using only use Git(Hub) and mail.

True, but it mandates the use of a web interface, which is a clumsy vehicle for speed conversation. Time is money. Better than gold.

**Comment by drawkula** [comment]
> True, but it mandates the use of a web interface, which is a clumsy
> vehicle for speed conversation. Time is money. Better than gold.

If you subscribed once via clickycoloured UI you get the issue mails
and can answer them by mail. So the conservation is comparable to being
done in a newsreader.

This sometimes has some glitches with formatting but (pointy ears mode)
in 92.572862% of the known cases it works (/pointy ears mode).

**Comment by src153** [comment]
Why don't I like email, you wonder?

Push vs pull

mailing list = push
newsreader = pull

I like to pull when I'm good and ready. The pull method is much better for casual observers who don't participate all the time, but like to check in now and then. You're not forced to keep up with a constant barrage of email from a list.

**Comment by src153** [comment]
To clarify my reason for this thread, so people don't misunderstand, and take it the wrong way.

My realistic goal is modest. I just wonder if there are any people interested in using a newsreader and a free server like Eternal September. In today's world, they are hard to find. Most people succumb to the ubiquitous web interface.

If there are people interested, we could use a newsgroup for chit chat about PC-MOS, things which are too noisy for the issues section. Some useful information may come from chit chat, and end up here. It could serve as a filter. Threads like this one litter the issues section, and distract people with excess mail.

If I can't find such people, I tried.

**Comment by stsp** [comment]
+1 for lowering traffic. Be it is a newsgroup
or anything else to accomplish this, I vote.

**Comment by src153** [comment]
> I already have between 500 and 1000+ messages on a daily basis

I could not do it. At some point you need to delegate.

> there is a moment when channeling the information is needed.

That's what I'm thinking.

**Comment by roelandjansen** [comment]
chitchat: telegram maybe? let's ude whatever works the best without too many nuisances for sure.

**Comment by src153** [comment]
Telegram? Nope. I'm not interested in smartphone instant messaging. I want to archive and search message history on a computer. A newsgroup pull technology is the answer. But nobody else cares. I give up.
