### ISSUE TITLE
Sealed envelope

### ISSUE THREAD

**Issue by src153** [roelandjansen/pcmos386v501#39]
Has anyone completed a simple install? The PCMOS386-9-user.img in IMAGES is much different from the files in SHIPMOS. You can boot the 9 user IMAGES floppy, but I don't see how it's useful after that. The system and auxiliary disks in SHIPMOS (once you create them from the files) let you do a floppy install from scratch.

So I did that, it worked, and now  I got this:
 
![image](https://user-images.githubusercontent.com/46651792/51442209-6b467400-1cd2-11e9-8107-311213f762b9.png)

I want the sealed envelope! Or at least knowledge of its contents.

**Comment by src153** [comment]
I continued with the next step, configuing with ACU. It added $386.SYS to config.sys. Then I rebooted, and it crashed. VMWARE 9 can't handle $386.sys.

I have real hardware to try it on, but the floppy install erases all hard disk partitions before it does anything else. At the moment I don't feel like opening a computer to swap hard drives, so that waits for later.

What I  wanted to learn most is, what happens with $$shell.sys and command.com?

$$shell.sys keeps its pre install size of 33794 bytes, and command.com is only 524 bytes, with a small blurb of code at the beginning. Wild guess, somehow invokes $$shell.sys.

But that begs the question, why is it backwards on PCMOS386-9-user.img in IMAGES?

**Comment by roelandjansen** [comment]
the sealed envelope contains a code that activates it to unlimited.
There is code that generates the code for you here as well.

Regarding command.com -- it does indeed pass on the stuff to $$shell.sys and command.com is backward-compatibility and required.



vmware 9? what is that?

**Comment by src153** [comment]
> the sealed envelope contains a code that activates it to unlimited.

How? Does it patch files? Is that all it does?

> There is code that generates the code for you here as well.

Where? How to use it?

> Regarding command.com -- it does indeed pass on the stuff to $$shell.sys and command.com is backward-compatibility and required.

The IMAGES command.com looks different. Very mysterious.

> vmware 9? what is that?

Virtualization environment software.
vmware.com
I have an old one, version 9.

**Comment by src153** [comment]
> Regarding command.com -- it does indeed pass on the stuff to $$shell.sys and command.com is backward-compatibility and required.

I've not yet seen in a makefile where it's created. Does anyone know?

**Comment by src153** [comment]
Now I  see SOURCES/src/sn/
OK. Thanks.

Good idea about removing the serial number code.

I still want to know where/how command.com is generated.

**Comment by the-grue** [comment]
Good find!  Leave it running for over an hour just to see if it times out on you.

**Comment by src153** [comment]
I don't see the 60 minute demo notice when it boots, so it's probably fine. But I'll let it run more than 1 hour, and advise.

In the SN directory, some ASM files talk about patching $$mos.sys, so diffing the two $$mos.sys files to see what changes may provide some insights. I won't do that now, just noting it for future reference.

I agree we should get rid of the serial number altogether, but it would be nice to have a working activator, so that when we remove the serial code, we know what we're doing, and don't miss anything. I like to have something to compare against.

**Comment by src153** [comment]
Or maybe that is all moot, if we build the R&D kernel instead of the eval. But is it safe to assume the R&D kernel is functionally identical to an activated eval? That is not clear to me at this point.

**Comment by src153** [comment]
Yes it passed the 1 hour test

![image](https://user-images.githubusercontent.com/46651792/51451020-23077000-1d2b-11e9-976d-8330793b6578.png)

**Comment by roelandjansen** [comment]
when home I'll check the tree and memory hopefully comes back on how to fix the eval stuff.

**Comment by roelandjansen** [comment]
the sn directory is indeed the place to be. I do not have a working eval vmware image right now on this laptop to test but I do recall that the activation was a piece of cake.

I'll see if I can get stuff working in my eat-at-work-time ;-)

**Comment by the-grue** [comment]
Ok, I am a heathen and unceremoniously opened the sealed envelope and it took me down the old "I wonder" path and sure enough I figured out the licensing tool and how to use it.

Basically, you'll need the MAKEUSER.EXE tool located in the sn directory.  You can follow along with this example if you have installed from the disks in the SHIPMOS directory.

On the boot screen, upper right area you'll see the serial number, probably 05-30041410.
Navigate to wherever you have the SOURCES\src\sn directory in your git repo or zip file you downloaded and extracted.
Type "makeuser /I 0530041410" (That is capital eye) followed by the serial number without the -.  
What you are looking for is output similar to the following:

0530041410,75NC

Which will be the first line following the banner and then it runs off a list of other serial,key combos.

Then, in your MOS install, go to the root directory and type "init 75NC":

![screenshot from 2019-01-22 19-08-03](https://user-images.githubusercontent.com/3101080/51580394-27da3a00-1e79-11e9-98a1-91866cc1f6d7.png)

And reboot.  You now have a licensed MOS system:

![screenshot from 2019-01-22 19-07-39](https://user-images.githubusercontent.com/3101080/51580380-1a24b480-1e79-11e9-887c-7c3810394dc9.png)

I had been messing with the MAKEUSER program a bit and the source code to try to figure it out and the missing piece was in the sheet of paper in the envelope, which showed the 4 digit code.  I remember having run the makeuser command with the /I and my serial number but the 4 digit codes and how to get them in the system eluded me.

I believe makeuser might have been a key generator program for TSL to create their serial number/key combinations for runs of disks.

Anyway, give it a try and see how it goes!

**Comment by the-grue** [comment]
About the 386.SYS issue.  Did you set the appropriate switch?  I set the MEMDEV option to /P to get it working.  It doesn't appear to have issues and I have upped my memory settings as far as 512M.  Also, you will probably want to disable hardware virtualization.  In VirtualBox, it is under System | Acceleration | Enable VT-x/AMD-V.  This is a requirement for a lot of older operating systems when they try to exit real mode and go into protected mode.  Not sure where that would be in VMWare, as I haven't used it in years.

**Comment by src153** [comment]
Thanks for those tips. I will look into it. If I supported 75 year copyrights, I wouldn't use VMWARE either.

**Comment by the-grue** [comment]
You're welcome.  If you hover over the MEMDEV setting in the ACU and press F2 (options) it shows you the possible settings.  I found /P to work for me, but there are other settings.

I was able to copy the 5.25 disks for version 4.0, but ran into 2 issues.

1. Blew the power supply on my Compaq Portable 286.  So I had to pull the drive and find a motherboard in my collection that would support a 5.25 drive.  Now I have another bench project to do.
2. The eval system disk is missing.  The system disk I have is the one with the registered copy of the kernel and shell and nothing else.  This is the one that was in the second envelope that was unsealed.  Not a big deal, as both of the auxiliary disks are present, but I am not sure what all is missing.  I know hdsetup, format, and msys are missing.  Probably install as well.  Oh, and obviously the eval kernel.

**Comment by src153** [comment]
Having 4.1, the manual, and the sealed envelope helps a lot. But if 4.0 is a problem, I would not spend more time on it.

**Comment by roelandjansen** [comment]
I will have the v5.0x manuals and probably disks today as a loaner from my long time Arjen Schouten.

**Comment by the-grue** [comment]
That's great news!  I am about half way through scanning the v4 documentation, then I need to convert it to searchable.  Takes a bit of time with a single side scanner.

**Comment by src153** [comment]
OK, closing.
