### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by the-grue** [roelandjansen/pcmos386v501#44]
Hi Roeland!  Can you create a Wiki for this project?  Might be good to document some of the things we are finding in a Wiki instead of having to search through open/closed issues, etc.

I think you just click that Wiki button right up there to set it up.

**Comment by roelandjansen** [comment]
https://github.com/roelandjansen/pcmos386v501/wiki

let me know if there are more needs.

**Comment by the-grue** [comment]
Only collaborators can edit the wiki unless you uncheck the "Restrict editing to collaborators only" checkbox on the Settings page.

Since nobody is designated a collaborator for this project, @roelandjansen is the only user that can edit it.

**Comment by roelandjansen** [comment]
ok, I can either open up for everyone, or add the collaborators. I am on a short break. The second one is the safest but...

**Comment by the-grue** [comment]
It's your project Roeland, so the decision is yours.  Otherwise, we can create a wiki section in the source code repo and drop stuff in there for you to promote to the actual wiki.

**Comment by src153** [comment]
What does everyone include? All github users? That is dangerous.

**Comment by the-grue** [comment]
I believe so.  It reads like you either have it only open to collaborators (which is different than contributors) or everybody.

**Comment by roelandjansen** [comment]
I lean towards collaborators then. when home I will double check.

**Comment by src153** [comment]
Done, closing
