### ISSUE TITLE
Ontrack Disk Manager

### ISSUE THREAD

**Issue by src153** [roelandjansen/pcmos386v501#48]
The user manual mentions Ontrack Disk Manager 4.02. Not sure if later versions work, but if anyone wants to try, 9.57 is freely available:

https://www.philscomputerlab.com/ontrack-disk-manager.html#

This may be a good item for the wiki, but ATM I don't know how

**Comment by roelandjansen** [comment]
when wiki is fixed, we'll "move" the info to it. good catch.

**Comment by roelandjansen** [comment]
I sent a few collabs a link so to be able to edit the wiki.

**Comment by src153** [comment]
In Wiki now, closing
