### ISSUE TITLE
Build depends on c:\tmp existing

### ISSUE THREAD

**Issue by dcoshea** [roelandjansen/pcmos386v501#5]
`SOURCES/src/MAKEMOS.BAT` includes the following code (as at 2d19bc1):

    set TMP=c:\TMP

When I performed a build, I noticed the following error fly by (manually transcribed, so apologies for any errors):

    link mosfront +mosint13 [...]
    Ndmake:  warning -- cannot open response file `c:\TMP\mk003683'.
    
    *** Error code 1

Since `MAKEMOS.BAT` causes there to be a requirement for this directory to exist, it'd be nice if it checked for its existence too.

Alternatively, or in addition to this, `README.md` could note that you need to create that directory before building.

I'll try to file a PR to add these sometime, but I'm not sure when I'll get around to it.

**Comment by roelandjansen** [comment]
good catch. 

I haven't created a virtual env to build it again myself, nor thought of a way to pull or push changes from there.

**Comment by dcoshea** [comment]
> I haven't created a virtual env to build it again myself, nor thought of a way to pull or push changes from there.

A somewhat off-topic discussion:

DOSBox would be very convenient since it requires little setup and it will mount a local directory as a DOS drive, so you can just set up some symlinks to your Git repository, but there's issue #6.

[Bochs](http://bochs.sourceforge.net/) will let you present a local directory to a virtual machine as a virtual VFAT filesystem ("vvfat"), as will [QEMU](https://www.qemu.org/), and they'll let you install whatever version of DOS you want, unlike DOSBox (which kind of does, but then loses the ability to mount a directory).  I tried with Bochs:
- It should hypothetically let you add an MBR image file and a bootsector image file into your directory so you can boot a DOS installation from a directory, but it didn't work for me.  I imagine that's because it's not presenting the `IO.SYS` and `MSDOS.SYS` files in my local directory as the first two files in the virtual VFAT filesystem.  I gave up on this.
- Another other option is to use a disk image for the first hard disk and vvfat for the second hard disk.  Two more options present themselves here:
  - Use these C: and D: drives normally, with the source code on D:, in which case `MAKEMOS.BAT` needs to be modified to use D: instead of C:.  There may be other files hard-coded to use C: too, I wouldn't know since I haven't tried this.
  - Copy the DOS files from C: to D:, then use `assign c=d` to redirect all access to C: to D:.  This worked for me (with MS-DOS 5).  In this case, C: merely needs to be bootable and have `ASSIGN.COM`, so it could be a tiny disk image.
- Alternatively, you could have a vvfat C: and just boot from a virtual floppy drive containing an `AUTOEXEC.BAT` that sets the PATH to include `C:\DOS5.0`, i.e. you only use the floppy because it's bootable, but don't use it after booting.  This might not be so convenient if you want to create PC-MOS bootable floppies using the VM; I don't know if that is something that one might want to do because I don't have any idea how it is done :)

Sadly the Bochs vvfat support seems to be buggy (I'm using the latest version 2.6.9) - it doesn't always write files back to your original directory, and sometimes filenames get combined for some reason, e.g. I ended up with a `SOURCES/src/mos5src/19term.sysUNTERM.PUB` file.

Perhaps a safer option is to run a network redirector and a file server, which would at least let you check file status from Git from outside the VM at the same time as the VM is running, since the above options don't allow (in the case of Bochs) or discourage (in the case of DOSBox) access to the files from the host while the guest is running.

**Comment by andrewbird** [comment]
Current MAKEMOS.BAT does `mkdir %TMP%` after setting it so this issue can probably be closed now.
