### ISSUE TITLE
5.01 code audit

### ISSUE THREAD

**Issue by src153** [roelandjansen/pcmos386v501#53]
I see it's merged. And now there are new questions.

I ran a diff on 501 vs 502 (5.01+ maybe?). Even after removing 3 files from 502 (the kernel still builds) which are not in 501, the diff is 29,651 lines. That's a lot to understand. Were those changes integrated and tested before they went out of business? Or do we have a buggy work in progress? How can we know, without a lot of trial and error?

The date bug was easy compared to this.

**Comment by the-grue** [comment]
Just some comments.  

1.  If the idea is to move forward, we can build the code in the "latest" directory and improve from there.  This includes code that is part of updat501.sys (see my audit documentation) at various versions.
2.  If the idea is to throw away any changes made post 5.01 and move forward, using mos501src for example, you'll end up dumping all fixes updat501.sys provides.
     a.  At some point, you will regress because updat501.sys will stop working.
     b.  When that happens, you will re-introduce any bugs updat501.sys may have fixed.
     c.  You are throwing away good code.
     d.  Which version of updat501.sys are we calling good?  I have identified at least 5 just in the repo:
          I.  1.36 in the 9-user image in IMAGES
          II.  1.24 in the 5 user disk extracts in SHIPMOS
          III.  0.07 in the jim directory source code
          IV.  1.13 in the kernel, mos5src directories source code (also in mos501src and latest)
          V.  1.41 in the booster pack
     e.  There may be more in the wild.

Personally, I am planning to do any future development in the "latest" tree and considering the other ones static/reference/archive from this point on.

**Comment by the-grue** [comment]
> The date bug was easy compared to this.

Haha!  Everything is easy once someone has proven it can be solved/done.  Proven fact, be it in coding, sports, whatever.  The "4 minute mile barrier" is a perfect example.  Or the 6+ years it took for someone to fix this "date bug".

I set out to solve the date bug as a personal quest/challenge.

Challenge accepted!  Quest completed!  Moving on...

**Comment by src153** [comment]
> If the idea is to move forward, we can build the code in the "latest" directory and improve from there. 

"We" won't be doing that.

> If the idea is to throw away any changes made post 5.01 and move forward, using mos501src for example, you'll end up dumping all fixes updat501.sys provides.

No true. I will use updat501.asm to build updat501.sys, and use it in config.sys

>        a.  At some point, you will regress because updat501.sys will stop working.

No it won't. I will freeze 501 with the two patches I mentioned, maybe cut a release, start a new tree based on that, update it with 29,000 lines of patches until I know what I'm doing.

> When that happens, you will re-introduce any bugs updat501.sys may have fixed.

Maybe you misunderstood what I said.

>        c.  You are throwing away good code.

Nope,

>        d.  Which version of updat501.sys are we calling good?  I have identified at least 5 just in the repo:
>        I.  1.36 in the 9-user image in IMAGES
>        II.  1.24 in the 5 user disk extracts in SHIPMOS
>        III.  0.07 in the jim directory source code
>        IV.  1.13 in the kernel, mos5src directories source code (also in mos501src and latest)
>        V.  1.41 in the booster pack

I'll start with 1.13 in the kernel and see how that goes.


> Personally, I am planning to do any future development in the "latest" tree and considering the other ones static/reference/archive from this point on.

I'm not using 29,000 lines of development diff, untested and unknown in production, until I understand it.

Happy trails.

**Comment by src153** [comment]
> 
> 
> > The date bug was easy compared to this.
> 
> Haha! Everything is easy once someone has proven it can be solved/done. Proven fact, be it in coding, sports, whatever. The "4 minute mile barrier" is a perfect example. Or the 6+ years it took for someone to fix this "date bug".
> 
> I set out to solve the date bug as a personal quest/challenge.
> 
> Challenge accepted! Quest completed! Moving on...

Not a personal challenge for me. I just wanted it fixed before spending any more of my time on PCMOS. Without it, I would lose interest.

**Comment by the-grue** [comment]
Ok, well have fun with your fork.  Just consider contributing back to the main project if you come up with anything of interest.

**Comment by src153** [comment]
To summarize, so that we're not mis-communicating:

The difference between your idea vs mine is simple. You're willing to take 29,000 lines of unverified development work on faith; I'm not. If God wrote that code, I WOULD take it on faith. But he didn't. Flawed humans in a company going bankrupt did. So I'm going to examine that code until I understand it. Which may be never. It's a lot to chew.

But what difference does it make anyway? Nobody cares enough to put serious work into this, except you and me. Roeland? He's reading 1,000 messages a day on his smartphone. He doesn't have time. And even if we could achieve an impossible dream, still no one would care. It's just hobby fun. There's never going to be another market for PCMOS.

So do what you like. I sure will.

**Comment by src153** [comment]
I read somewhere that someone still using PCMOS in 2012 was hit by date the bug, and they worked around it by setting the  system date back, and compensatiing in their application. On the chance any of those people are still doing that in 2109, maybe you should put a binary patch together for them. I would not provide a complete image though, just the patch bytes, with somesafeguard they are patching the right file. RTpatch maybe? I don't know, never really looked into doing that.

**Comment by src153** [comment]
Or maybe your patch wil break something and they will sue you. TSL got sued once. Better provide it anonymously then. And don't sue me, I do not provide legal advice. This is just idle chatter.

**Comment by roelandjansen** [comment]
ok guys. calm down. This all is open source.  It's fine if someone disagrees on how the merging went.
Anyone is free to redo it for themselves and come up with a PR that fixes issues. I am pretty sure everybody tries to do their utmost to fix things and give the best ideas.

So let's move forward.

**Comment by the-grue** [comment]
We're all good.  Just some friendly debate.

**Comment by src153** [comment]
I think this is settled now, closing
