### ISSUE TITLE
5.01 distribution with date bug fixed

### ISSUE THREAD

**Issue by src153** [roelandjansen/pcmos386v501#56]
@sub205 Tell me if you want this work. There will be much to discuss, we can do it here.

**Comment by src153** [comment]
sub205 declined. Anyone else? If not, I will close soon.

**Comment by sub205** [comment]
I already did the work, you declined to merge it back in the main project!

**Comment by sub205** [comment]
Ok, then please tell me exactly what it is you wanted!

We got a ready distribution which - we all agreed - don't want to modify to much to get a nearly original 5.01 without the date-bug.

The easiest way to accomplish this is to take the original, just fix the 31-07-2012-date-bug and leave the rest as it was intended from the developers back in those days.

You said you want as less patches as possible. What else can be better than a patch that only changes 1 single byte in the entire image?

Maybe we just talk past each other?

**Comment by src153** [comment]
We're in agreement on that.

But there is another small patch submitted by Stas (stsp) which also fixes a typo. It should not change the size the size of the object. I want you to look into that, and verify that I'm correct.

In addition to a binary patch. I want you to build from source and produce an indentical $$mos.sys binary, verify that we have everything correct.

Then, convert the SHIPMOS zip files to a corresponding SYSTEM bootable image and its companion AUXILIARY disk (I'm not interested in BOOSTER, it's a binary blob). No need to patch the original ZIP files, they're just historical now. Our new images will supersede them.

**Comment by src153** [comment]
There's more to discuss, but that will get you started.

The resulting floppy images should be placed IMAGES / v5.01 , like  IMAGES / v4 provided by @the-grue. The existing 9 user images and associated README file should be placed in IMAGES / v5.01-live-floppy, to indicate they are not a true install set.

**Comment by src153** [comment]
@sub205 I need confirmation that you're interested, and have time for this. If not, I will proceed at my own slow pace.

**Comment by sub205** [comment]
i'm currently in the process of setting up a development environment.
I don't know much about the build process right now, tested it a year ago and ran into issues.
Is it just as simple as running MAKEMOS.BAT right now?

**Comment by src153** [comment]
You only need the part of MAKEMOS where it builds the kernel. And you need to change that back to the way it used to be, and build the eval, not the R & D kernel.

Tell me about your environment, maybe I will have some ideas to help you speed things along.

**Comment by src153** [comment]
Any OS that works for you. Doesn't matter. The finished product, $$MOS.SYS is all that matters for this work.

I just wanted to confirm you can do it. The date bug went unfixed for a year. No need to rush now.

**Comment by sub205** [comment]
I'll try to and give you feedback.

Alternatively, i can patch any existing binary (diskimage or $$MOS.SYS) directly, because the change in the assemblercode is just changing a byte.

**Comment by src153** [comment]
Work on the souce build first. @the-grue said he could assist with a binary patch.

We don't even need a binary patch for our own purposes. Once you build from source, we can do a binary compare to a patched image, to confirm we are correct.

The idea of having a binary patch utility is for the pubic, who may want to patch their own local image. But that's optional, and can wait for later.

**Comment by sub205** [comment]
$$MOS.SYS built successfully.
Any ideas on how to get proper images of v5.01?
Are there any tools or scripts to do this?

**Comment by src153** [comment]
The image you need to compare to is found in

https://github.com/roelandjansen/pcmos386v501/blob/master/SHIPMOS/1_MOS5userSystemSN0530041410.zip

Once you get it out of the ZIP file, the first problem you will find is, the serial numbers don't match.  The image you built just has some generic junk for the serial number. You will need to boot the SHIPMOS disk to see what its serial number is. And then you will need to fix up the source to use the same serial number, and build again. If you can't boot the SHIPMOS disk, maybe I have a screen shot that shows the official serial number, and that will save you some time.

https://github.com/roelandjansen/pcmos386v501/pull/54#issuecomment-460016015

**Comment by the-grue** [comment]
The serial number is in the filename.  05-30041410

See my comments in #39 as well if you want to activate it.

As @src153 mentions above, #54 tells you where it is set in the source.  You could just drop in 0530041410 in place of X0X0X0X0X0.

**Comment by sub205** [comment]
Anyone a clue with what version of pkzip MOSFILES.EXE / AUXFILES.EXE was created?
We have to repack those, too, because - as far as i can see - the shipmos-stuff is v5.0 with a v5.01 patch that gets loaded in config.sys ?!

Best way would be a script to do all this stuff because we will have to do this over and over again in the future.

**Comment by src153** [comment]
Oh wait, I do know what you're talking about. DONT MESS WITH those two files. YOU MUST NOT EXPAND THEM. The installation program does that automatically when you boot the SYSTEM floppy and install.

**Comment by the-grue** [comment]
> Anyone a clue with what version of pkzip MOSFILES.EXE / AUXFILES.EXE was created?

Try extracting pkz110.exe in the BIN directory.  That will give you pkzip.exe.  There is already a zip2exe.exe in the BIN directory, but I don't know if it is the same one.  I plan to use these since they are provided already.

**Comment by src153** [comment]
Try not to make this harder than it is. Just follow the yellow brick road.

**Comment by src153** [comment]
You don't need to repack anything. We're not changing any of that stuff. All we care about right now is $$MOS.SYS

Don't overthink this.

**Comment by sub205** [comment]
@src153 got it, but i only want to know what UPDAT501.SYS is all about.

Does it patch the running $$MOS.SYS and do we - maybe - get problems later on, because there are fixed offsets inside that now are not valid anymore?

**Comment by the-grue** [comment]
@sub205 the latest source code we have for UPDAT501.SYS is UPDAT501.ASM in the code directory.  Assuming you guys are still looking either in the kernel or mos501src directories as your 5.01 base.

Keep in mind that this isn't necessarily at the same level as what is in the 5 user images.  I wrote the variances up in another thread, but it seems each version has a different level of UPDAT501.SYS and each of those is different than the source code available for that driver file.

Another option is disassembly of the version in the 5 user disk set and tweak it so it can be reassembled to original size/checksummed version.

**Comment by sub205** [comment]
Ok. Got serial and stuff right, will do the rest tomorrow because it's already late here.

**Comment by src153** [comment]
Trust me, I did not lure you into a black hole of endlesss work. What we want to do is not that hard, and won't take that long.

When you have a question on how to proceed, instead of getting sidetracked, just ask. I could do this myself, but it's a good excercise for other people to get involved.

**Comment by src153** [comment]
For now we will use the updat501.sy from the official distribution. There are other versions, but we won't worry about them right how. My assumption is, that by keeping the SIZE of $$MOS.SYS the same, updat501.SYS from the official distrbution will work fine. But that's what we must test and find out. If successful, we're done.

**Comment by src153** [comment]
For tomorrow when you see this, don't use the date patch in your source build, at least not yet. Just try to build a binary $$MOS.SYS which is identical to the one from SHIPMOS SYSTEM ZIP. If you can do that, we're almost home. If not, we'll have to chase down why they're different. Which source direcotry are you building the kernel from?

**Comment by src153** [comment]
I should also say, you can't build the kernel using the current git source, because it has extra patches which increase the size of object. That's no good for our purposes. You must find the archived KERNEL.ZIP in the /ref directory, expand it, and build from that. It contains existing .obj files, so be sure to delete them first.

I did that, and the object sizes are identical. We're getting warm, but we're not home yet. You'll see what I mean.

**Comment by sub205** [comment]
pull request pending.

**Comment by sub205** [comment]
@src152 Are you kidding me?
Leaving the project and still playing "the great leader" here?!
Do this in your own fork!

**Comment by src153** [comment]
It was my thread, so I closed it. What's your problem? Your pull request is not affected.
