### ISSUE TITLE
GEM 3.13 - MOS GUI?

### ISSUE THREAD

**Issue by the-grue** [roelandjansen/pcmos386v501#66]
Not really an issue, so I'll be brief, GEM was open sourced years ago.  It works in MOS.  If you want to play with a GUI, give it a look.

![screenshot from 2019-02-04 12-56-35](https://user-images.githubusercontent.com/3101080/52236815-bb9a0600-287c-11e9-9a75-863e5d01e8b4.png)

**Comment by src153** [comment]
The wiki is not tricky. If I can do it, anybody can.

**Comment by roelandjansen** [comment]
See also https://winworldpc.com/product/gem/3x  -- I'll add it to the wiki.
