### ISSUE TITLE
civilization, being rude etc

### ISSUE THREAD

**Issue by roelandjansen** [roelandjansen/pcmos386v501#67]
let's all except for @src153, agree that we're people who can disagree or agree on things without 
being rude.

As per his request and also backed by the way some people felt the mistreatment they received,  I have removed him from the project. I hope that @andrewbird and others may reconsider coming back. 

I hope that we can continue the work and fun we have of this project and wish @src153 all the luck.

Anyone that feels that a specific issue was closed without enough reason, we'll reopen.

Roeland

**Comment by roelandjansen** [comment]
and, since i felt that even withdrawing rights was not enough, I have - fully against my normal way of working - to active block a member here. Sometimes it's the only way to get rid of the negative vibes some people want to spread.

**Comment by drawkula** [comment]
> fully against my normal way of working

I know that feeling from having been caretaker in some chats.
It feels like a defeat but it needs to be done.

Thanks!
