### ISSUE TITLE
60 Minute Demo?

### ISSUE THREAD

**Issue by stsp** [roelandjansen/pcmos386v501#90]
rel 5.02 says this:
```
PC-MOS is a registered trademark of The Software Link, Inc.
 
(c) Copyright 1987-1992 The Software Link, Incorporated               rel 5.02
All rights reserved worldwide                                      25-50214833
 
60 Minute Demo Disk Version
```

Which looks wrong.

**Comment by the-grue** [comment]
Run "regme.bat".  It's in the readme file...

**Comment by the-grue** [comment]
Also, if you play with the CDROM driver, you'll notice I didn't remove the 30 minute demo message in there either.  It wasn't my goal to completely fix every cosmetic blemish in the OS.

This particular one, I made a workaround for now and documented it.

**Comment by the-grue** [comment]
CDROM driver fixed under pull request #91

**Comment by the-grue** [comment]
MOS will also auto-register the kernel during build now when using makeall.bat.  This is an additional update in #91

**Comment by stsp** [comment]
Thanks!
